---

- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: "Install nginx"
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: true

- name: "Ensure Nginx is started and enabled"
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

- name: "Nginx conf"
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: preserve
  notify: restart nginx
